[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.2"
num-bigint = "0.4.3"
serde = {version = "1.0", features= ["derive"]}
macros = { path = "../macros" }
bitflags = "2.0.0-rc.1"