[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.3"
yaserde = {version = "0.7.1"}
yaserde_derive = "0.7.1"
xsd-types = { git = "https://github.com/lumeohq/xsd-parser-rs", rev = "d8dd37e" }
xsd-macro-utils = { git = "https://github.com/lumeohq/xsd-parser-rs", rev ="d8dd37e" }
xsd-parser = { git = "https://github.com/lumeohq/xsd-parser-rs", rev = "d8dd37e" }
xml-rs = "0.8.4"
