//! Example serialisations of IEEE 2030.5 Resources, copied from the specification - locked behind the

pub const ED_16_01_08: &str = r#"<EndDevice href="/edev/3" subscribable="0" xmlns="urn:ieee:std:2030.5:ns"><ConfigurationLink href="/edev/3/cfg"/><DeviceInformationLink href="/edev/3/di"/><DeviceStatusLink href="/edev/3/ds"/><FileStatusLink href="/edev/3/fs"/><PowerStatusLink href="/edev/3/ps"/><sFDI>987654321005</sFDI><changedTime>1379905200</changedTime><FunctionSetAssignmentsListLink all="3" href="/edev/3/fsal"/><RegistrationLink href="/edev/3/reg"/><SubscriptionListLink all="0" href="/edev/3/subl"/></EndDevice>"#;
pub const REG_16_01_10: &str = r#"<Registration href="/edev/3/reg" xmlns="urn:ieee:std:2030.5:ns"><dateTimeRegistered>1364774400</dateTimeRegistered><pIN>123455</pIN></Registration>"#;
pub const EDL_16_02_08: &str = r#"<EndDeviceList all="1" href="/edev" results="1" subscribable="0" xmlns="urn:ieee:std:2030.5:ns"><EndDevice href="/edev/3" subscribable="0"><ConfigurationLink href="/edev/3/cfg"/><DeviceInformationLink href="/edev/3/di"/><DeviceStatusLink href="/edev/3/ds"/><FileStatusLink href="/edev/3/fs"/><PowerStatusLink href="/edev/3/ps"/><sFDI>987654321005</sFDI><changedTime>1379905200</changedTime><FunctionSetAssignmentsListLink all="3" href="/edev/3/fsal"/><RegistrationLink href="/edev/3/reg"/><SubscriptionListLink all="0" href="/edev/3/subl"/></EndDevice></EndDeviceList>"#;
// s/3/4
pub const ED_16_03_06: &str = r#"<EndDevice href="/edev/4" subscribable="0" xmlns="urn:ieee:std:2030.5:ns"><ConfigurationLink href="/edev/4/cfg"/><DeviceInformationLink href="/edev/4/di"/><DeviceStatusLink href="/edev/4/ds"/><FileStatusLink href="/edev/4/fs"/><PowerStatusLink href="/edev/4/ps"/><sFDI>987654321005</sFDI><changedTime>1379905200</changedTime><FunctionSetAssignmentsListLink all="2" href="/edev/4/fsal"/><RegistrationLink href="/edev/4/reg"/><SubscriptionListLink all="0" href="/edev/4/subl"/></EndDevice>"#;
// s/3/4
pub const FSAL_16_03_11: &str = r#"<FunctionSetAssignmentsList all="2" href="/edev/4/fsal" results="2" subscribable="0" xmlns="urn:ieee:std:2030.5:ns"><FunctionSetAssignments href="/edev/4/fsal/0" subscribable="0"><DemandResponseProgramListLink all="2" href="/edev/4/fsa1/0/drpl"/><MessagingProgramListLink all="1" href="/edev/4/fsa1/0/msgl"/><mRID>0ED30F5A0000</mRID><description>FunctionSetAssignment Suave</description></FunctionSetAssignments><FunctionSetAssignments href="/edev/4/fsal/1" subscribable="0"><MessagingProgramListLink all="1" href="/edev/4/fsa1/1/msgl"/><mRID>0ED30F5A0001</mRID><description>FunctionSetAssignment Guttural</description></FunctionSetAssignments></FunctionSetAssignmentsList>"#;
// s/3/5
pub const ER_16_04_06: &str = r#"<EndDevice href="/edev/5" subscribable="0" xmlns="urn:ieee:std:2030.5:ns"><ConfigurationLink href="/edev/5/cfg"/><DeviceInformationLink href="/edev/5/di"/><DeviceStatusLink href="/edev/5/ds"/><FileStatusLink href="/edev/5/fs"/><PowerStatusLink href="/edev/5/ps"/><sFDI>987654321005</sFDI><changedTime>1379905200</changedTime><RegistrationLink href="/edev/5/reg"/><SubscriptionListLink all="0" href="/edev/5/subl"/></EndDevice>"#;
pub const DC_16_04_11: &str = r#"<DeviceCapability href="/dcap" xmlns="urn:ieee:std:2030.5:ns"><DemandResponseProgramListLink all="1" href="/drp"/><MessagingProgramListLink all="2" href="/msg"/><EndDeviceListLink all="1" href="/edev"/><SelfDeviceLink href="/sdev"/></DeviceCapability>"#;
pub const NTF_16_06_04: &str = r#"<Notification xmlns="urn:ieee:std:2030.5:ns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><subscribedResource>/upt/0/mr/4/r</subscribedResource><Resource xsi:type="Reading"><timePeriod><duration>0</duration><start>12987364</start></timePeriod><value>1001</value></Resource><status>0</status><subscriptionURI>/edev/8/sub/5</subscriptionURI></Notification>"#;
